name: CI

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --locked

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Check imports and linting
        run: uv run ruff check .

      - name: Run unit tests with coverage
        run: uv run pytest --cov=game_vault --cov-report=term-missing

      - name: Bandit by PyCQA
  # You may pin to the exact commit or the version.
  # uses: PyCQA/bandit-action@67a458d90fa11fb1463e91e7f4c8f068b5863c7f
  uses: PyCQA/bandit-action@v1.0.1
  with:
    targets: .
